/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_boom_JNITest */

#ifndef _Included_com_boom_JNITest
#define _Included_com_boom_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_boom_JNITest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_boom_JNITest_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_boom_JNITest
 * Method:    getString2FromC
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_boom_JNITest_getString2FromC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_boom_JNITest
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_boom_JNITest_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    accessConstaructor
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_boom_JNITest_accessConstaructor
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    accessNovirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_accessNovirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_boom_JNITest_chineseChars
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_boom_JNITest
 * Method:    giveArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_giveArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_boom_JNITest
 * Method:    getArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_boom_JNITest_getArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_boom_JNITest
 * Method:    localRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_localRef
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    createGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_createGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    getGloballRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_boom_JNITest_getGloballRef
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    deleteGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_deleteGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_boom_JNITest
 * Method:    exception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_boom_JNITest_exception
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
